version: "2"
services:

    app:
        build: ./drivers
        ports:
            - "80:80"
        links:
            - mysql:mysql_conn
            - redis:redis_conn
        environment:
            - FLASK_CONFIG=development
            - TZ=PRC
        volumes:
            - ./data/graphs:/app/static/images/graphs

    mysql:
        image: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql/data:/var/lib/mysql
        environment:
            - TZ=PRC
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=drivers
            - MYSQL_PASSWORD=1234
            - MYSQL_DATABASE=dirvers

    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis/data:/data
        command: ["redis-server", "--appendonly", "yes"]
